Sample story
案例故事

Narrative:
In order to communicate effectively to the business some functionality
As a development team
I want to use Behaviour-Driven Development
为了更好的把商业需求传递出去
作为一个开发团队
我希望使用行为驱动开发
					 
Scenario:  A scenario is a collection of executable steps of different type
Given 给定一个 5 乘 5 的游戏
When 当我点击了 (2, 3) 这个位置的时候
Then 游戏棋盘应该像以下这样子
.....
.....
.....
..X..
.....
When 当我点击了 (2, 4) 这个位置的时候
Then 游戏棋盘应该像以下这样子
.....
.....
.....
..X..
..X..
When 当我点击了 (2, 3) 这个位置的时候
Then 游戏棋盘应该像以下这样子
.....
.....
.....
.....
..X..